export const AGENT_CHANNELS = {
  dispatchCommand: 'agent:dispatch-command',
  subscribeThread: 'agent:subscribe-thread',
  unsubscribeThread: 'agent:unsubscribe-thread',
  subscribeShell: 'agent:subscribe-shell',
  unsubscribeShell: 'agent:unsubscribe-shell',
  getShellSnapshot: 'agent:get-shell-snapshot',
  interruptTurn: 'agent:interrupt-turn',
  respondToApproval: 'agent:respond-to-approval',
  respondToUserInput: 'agent:respond-to-user-input',
  stopSession: 'agent:stop-session',
  listProviders: 'agent:list-providers',
  listModelCatalog: 'agent:list-model-catalog',
  clearThread: 'agent:clear-thread',
  getCheckpointDiff: 'agent:get-checkpoint-diff',
  getCheckpointWorktreeDiff: 'agent:get-checkpoint-worktree-diff',
  getWorkspaceDiff: 'agent:get-workspace-diff',
  openWorkspaceFolder: 'agent:open-workspace-folder',
  revealPath: 'agent:reveal-path',
  appendDebugTrace: 'agent:append-debug-trace',
  threadEvent: (subscriptionId: string) => `agent:thread-event:${subscriptionId}`,
  shellEvent: (subscriptionId: string) => `agent:shell-event:${subscriptionId}`
} as const
